apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-express-deployment
  labels:
    app: mongo-express

spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: mongo-express
  
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.2-20-alpine3.19
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef: 
              name: mongo-express-secret
              key: mongo-express-admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongo-express-secret
              key: mongo-express-password    
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            secretKeyRef: 
              name: mongo-express-secret
              key: mongo-express-server


---
apiVersion: v1 
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports: 
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30021
