apiVersion: v1 
kind: Secret 
metadata: 
  name: mongo-express-secret
type: Opaque
data: 
  mongo-express-admin: aWFtcmlkb3lkZXkK
  mongo-express-password: bW9uZ29wYXNzd29yZAo=
  mongo-express-server: bW9uZ28K