version: "3"
services:
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iamridoydey
      - MONGO_INITDB_ROOT_PASSWORD=iamridoydey
    volumes:
      - mymongo-data-one:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=iamridoydey
      - ME_CONFIG_MONGODB_ADMINPASSWORD=iamridoydey
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mymongo-data-one:
    driver: local