# Deployment and service in 1 file, because they are belong together

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1

  # Define pods belongs to deployment
  selector:
    matchLabels:
      app: mongo

  # Configure the pod
  template:
    metadata:
      labels:
        app: mongo
    spec:
    # Configure deployment to create pod with mongo:8.0
      containers:
      - name: mongo
        image: mongo:8.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # Select the pods to forward the requests to
  selector:
    app: mongo
  ports:
    - name: http
      protocol: TCP
      # Requested Port
      port: 8080
      # Mongo Service - ContainerPort of Deployment
      targetPort: 27017
